/*******************************************************************************
 *
 * Copyright (C) 2020 MyDefence Communication ApS. All rights reserved.
 *
 * These computer program listings and specifications, are the property of
 * MyDefence Communication ApS and shall not be reproduced or copied or used in
 * whole or in part without written permission from MyDefence Communication A/S.
 *
 * Autogenerated Argos API typescript types. DO NOT EDIT!
 *
 *******************************************************************************/
import { Alarm } from './auto/Alarm';
export { Alarm } from './auto/Alarm';
import { AlarmZoneAdd } from './auto/AlarmZoneAdd';
export { AlarmZoneAdd } from './auto/AlarmZoneAdd';
import { AlarmZoneId } from './auto/AlarmZoneId';
export { AlarmZoneId } from './auto/AlarmZoneId';
import { Error } from './auto/Error';
export { Error } from './auto/Error';
import { AlarmZone } from './auto/AlarmZone';
export { AlarmZone } from './auto/AlarmZone';
import { AlarmZoneList } from './auto/AlarmZoneList';
export { AlarmZoneList } from './auto/AlarmZoneList';
import { ApiError } from './auto/ApiError';
export { ApiError } from './auto/ApiError';
import { CompositeDeviceAdd } from './auto/CompositeDeviceAdd';
export { CompositeDeviceAdd } from './auto/CompositeDeviceAdd';
import { DeviceId } from './auto/DeviceId';
export { DeviceId } from './auto/DeviceId';
import { DeviceAdd } from './auto/DeviceAdd';
export { DeviceAdd } from './auto/DeviceAdd';
import { DeviceSerialNumberError } from './auto/DeviceSerialNumberError';
export { DeviceSerialNumberError } from './auto/DeviceSerialNumberError';
import { Device } from './auto/Device';
export { Device } from './auto/Device';
import { DeviceCalibrationStart } from './auto/DeviceCalibrationStart';
export { DeviceCalibrationStart } from './auto/DeviceCalibrationStart';
import { DeviceDeviceIdError } from './auto/DeviceDeviceIdError';
export { DeviceDeviceIdError } from './auto/DeviceDeviceIdError';
import { DeviceList } from './auto/DeviceList';
export { DeviceList } from './auto/DeviceList';
import { DeviceLocationChange } from './auto/DeviceLocationChange';
export { DeviceLocationChange } from './auto/DeviceLocationChange';
import { DeviceLocation } from './auto/DeviceLocation';
export { DeviceLocation } from './auto/DeviceLocation';
import { DeviceLocationList } from './auto/DeviceLocationList';
export { DeviceLocationList } from './auto/DeviceLocationList';
import { DeviceMiscellaneousList } from './auto/DeviceMiscellaneousList';
export { DeviceMiscellaneousList } from './auto/DeviceMiscellaneousList';
import { DeviceMiscellaneousChange } from './auto/DeviceMiscellaneousChange';
export { DeviceMiscellaneousChange } from './auto/DeviceMiscellaneousChange';
import { DeviceMiscellaneousInfo } from './auto/DeviceMiscellaneousInfo';
export { DeviceMiscellaneousInfo } from './auto/DeviceMiscellaneousInfo';
import { EcmConfig } from './auto/EcmConfig';
export { EcmConfig } from './auto/EcmConfig';
import { TimeInterval } from './auto/TimeInterval';
export { TimeInterval } from './auto/TimeInterval';
import { EcmHistory } from './auto/EcmHistory';
export { EcmHistory } from './auto/EcmHistory';
import { EcmState } from './auto/EcmState';
export { EcmState } from './auto/EcmState';
import { FeatureList } from './auto/FeatureList';
export { FeatureList } from './auto/FeatureList';
import { FwuImageAdd } from './auto/FwuImageAdd';
export { FwuImageAdd } from './auto/FwuImageAdd';
import { FwuImage } from './auto/FwuImage';
export { FwuImage } from './auto/FwuImage';
import { FwuImageList } from './auto/FwuImageList';
export { FwuImageList } from './auto/FwuImageList';
import { FwuImageId } from './auto/FwuImageId';
export { FwuImageId } from './auto/FwuImageId';
import { DeviceIds } from './auto/DeviceIds';
export { DeviceIds } from './auto/DeviceIds';
import { FwuUpdateableList } from './auto/FwuUpdateableList';
export { FwuUpdateableList } from './auto/FwuUpdateableList';
import { MissionCenter } from './auto/MissionCenter';
export { MissionCenter } from './auto/MissionCenter';
import { OriginFilterAdd } from './auto/OriginFilterAdd';
export { OriginFilterAdd } from './auto/OriginFilterAdd';
import { OriginFilterId } from './auto/OriginFilterId';
export { OriginFilterId } from './auto/OriginFilterId';
import { OriginFilter } from './auto/OriginFilter';
export { OriginFilter } from './auto/OriginFilter';
import { OriginFilterList } from './auto/OriginFilterList';
export { OriginFilterList } from './auto/OriginFilterList';
import { PtzDeviceInfo } from './auto/PtzDeviceInfo';
export { PtzDeviceInfo } from './auto/PtzDeviceInfo';
import { PtzDeviceList } from './auto/PtzDeviceList';
export { PtzDeviceList } from './auto/PtzDeviceList';
import { PtzDeviceSet } from './auto/PtzDeviceSet';
export { PtzDeviceSet } from './auto/PtzDeviceSet';
import { PtzFollowList } from './auto/PtzFollowList';
export { PtzFollowList } from './auto/PtzFollowList';
import { PtzFollowStart } from './auto/PtzFollowStart';
export { PtzFollowStart } from './auto/PtzFollowStart';
import { PtzFollowId } from './auto/PtzFollowId';
export { PtzFollowId } from './auto/PtzFollowId';
import { PtzFollow } from './auto/PtzFollow';
export { PtzFollow } from './auto/PtzFollow';
import { PtzMoveAbs } from './auto/PtzMoveAbs';
export { PtzMoveAbs } from './auto/PtzMoveAbs';
import { PtzSetVelocity } from './auto/PtzSetVelocity';
export { PtzSetVelocity } from './auto/PtzSetVelocity';
import { RfGeoThreatSimulationResult } from './auto/RfGeoThreatSimulationResult';
export { RfGeoThreatSimulationResult } from './auto/RfGeoThreatSimulationResult';
import { RfGeoThreatSimulationStart } from './auto/RfGeoThreatSimulationStart';
export { RfGeoThreatSimulationStart } from './auto/RfGeoThreatSimulationStart';
import { RfGeoThreatSimulationStartCompleted } from './auto/RfGeoThreatSimulationStartCompleted';
export { RfGeoThreatSimulationStartCompleted } from './auto/RfGeoThreatSimulationStartCompleted';
import { RfGeoThreatSimulationStartError } from './auto/RfGeoThreatSimulationStartError';
export { RfGeoThreatSimulationStartError } from './auto/RfGeoThreatSimulationStartError';
import { RfRecordList } from './auto/RfRecordList';
export { RfRecordList } from './auto/RfRecordList';
import { RfRecordThreatsConfig } from './auto/RfRecordThreatsConfig';
export { RfRecordThreatsConfig } from './auto/RfRecordThreatsConfig';
import { SapientConfiguration } from './auto/SapientConfiguration';
export { SapientConfiguration } from './auto/SapientConfiguration';
import { SapientConfigure } from './auto/SapientConfigure';
export { SapientConfigure } from './auto/SapientConfigure';
import { SapientNodeList } from './auto/SapientNodeList';
export { SapientNodeList } from './auto/SapientNodeList';
import { SapientNode } from './auto/SapientNode';
export { SapientNode } from './auto/SapientNode';
import { SystemLog } from './auto/SystemLog';
export { SystemLog } from './auto/SystemLog';
import { SystemLogList } from './auto/SystemLogList';
export { SystemLogList } from './auto/SystemLogList';
import { SystemState } from './auto/SystemState';
export { SystemState } from './auto/SystemState';
import { TakConfiguration } from './auto/TakConfiguration';
export { TakConfiguration } from './auto/TakConfiguration';
import { TakConfigure } from './auto/TakConfigure';
export { TakConfigure } from './auto/TakConfigure';
import { TakTransportList } from './auto/TakTransportList';
export { TakTransportList } from './auto/TakTransportList';
import { TakTransport } from './auto/TakTransport';
export { TakTransport } from './auto/TakTransport';
import { ThreatTypeList } from './auto/ThreatTypeList';
export { ThreatTypeList } from './auto/ThreatTypeList';
import { ThreatType } from './auto/ThreatType';
export { ThreatType } from './auto/ThreatType';
import { Time } from './auto/Time';
export { Time } from './auto/Time';
import { Uthreat } from './auto/Uthreat';
export { Uthreat } from './auto/Uthreat';
import { UthreatConfig } from './auto/UthreatConfig';
export { UthreatConfig } from './auto/UthreatConfig';
import { UthreatGetHistoryData } from './auto/UthreatGetHistoryData';
export { UthreatGetHistoryData } from './auto/UthreatGetHistoryData';
import { UthreatHistory } from './auto/UthreatHistory';
export { UthreatHistory } from './auto/UthreatHistory';
import { UthreatHistoryData } from './auto/UthreatHistoryData';
export { UthreatHistoryData } from './auto/UthreatHistoryData';
import { UthreatSetMute } from './auto/UthreatSetMute';
export { UthreatSetMute } from './auto/UthreatSetMute';
import { VmsSdpInit } from './auto/VmsSdpInit';
export { VmsSdpInit } from './auto/VmsSdpInit';
import { VmsSdpInitCompleted } from './auto/VmsSdpInitCompleted';
export { VmsSdpInitCompleted } from './auto/VmsSdpInitCompleted';
import { VmsStreamList } from './auto/VmsStreamList';
export { VmsStreamList } from './auto/VmsStreamList';
export type AlarmStarted = Alarm;
export type AlarmStopped = Alarm;
export type AlarmUpdated = Alarm;
export type AlarmZoneAddCompleted = AlarmZoneId;
export type AlarmZoneAddError = Error;
export type AlarmZoneAdded = AlarmZone;
export type AlarmZoneGetList = Empty;
export type AlarmZoneRemove = AlarmZoneId;
export type AlarmZoneRemoveCompleted = AlarmZoneId;
export type AlarmZoneRemoveError = Error;
export type AlarmZoneRemoved = AlarmZoneId;
export type AlarmZoneUpdate = AlarmZone;
export type AlarmZoneUpdateCompleted = AlarmZoneId;
export type AlarmZoneUpdateError = Error;
export type AlarmZoneUpdated = AlarmZone;
export type CompositeDeviceAddCompleted = DeviceId;
export type CompositeDeviceAddError = Error;
export type DeviceAddCompleted = DeviceId;
export type DeviceAddError = DeviceSerialNumberError;
export type DeviceAdded = Device;
export type DeviceCalibrationStartCompleted = DeviceId;
export type DeviceCalibrationStartError = DeviceDeviceIdError;
export type DeviceGetList = Empty;
export type DeviceGetLocations = DeviceId;
export type DeviceGetMiscellaneous = DeviceId;
export type DeviceLocationChangeCompleted = DeviceId;
export type DeviceLocationChangeError = DeviceDeviceIdError;
export type DeviceLocationChanged = DeviceLocation;
export type DeviceLocations = DeviceLocationList;
export type DeviceMiscellaneous = DeviceMiscellaneousList;
export type DeviceMiscellaneousChangeCompleted = DeviceId;
export type DeviceMiscellaneousChangeError = DeviceDeviceIdError;
export type DeviceMiscellaneousChanged = DeviceMiscellaneousInfo;
export type DeviceMount = DeviceId;
export type DeviceMountCompleted = DeviceId;
export type DeviceMountError = DeviceDeviceIdError;
export type DeviceRemove = DeviceId;
export type DeviceRemoveCompleted = DeviceId;
export type DeviceRemoveError = DeviceDeviceIdError;
export type DeviceRemoved = Device;
export type DeviceUnmount = DeviceId;
export type DeviceUnmountCompleted = DeviceId;
export type DeviceUnmountError = DeviceDeviceIdError;
export type DeviceUpdated = Device;
export type EcmConfiguration = EcmConfig;
export type EcmConfigure = EcmConfig;
export type EcmConfigureCompleted = EcmConfig;
export type EcmConfigureError = Error;
export type EcmGetConfiguration = Empty;
export type EcmGetHistory = TimeInterval;
export type EcmGetState = DeviceId;
export type EcmStart = DeviceId;
export type EcmStartCompleted = DeviceId;
export type EcmStartError = DeviceDeviceIdError;
export type EcmStop = DeviceId;
export type EcmStopCompleted = DeviceId;
export type EcmStopError = DeviceDeviceIdError;
export type EcmUpdated = EcmState;
export type FeatureGetList = Empty;
export type FwuImageAddCompleted = FwuImage;
export type FwuImageAddError = Error;
export type FwuImageAdded = FwuImage;
export type FwuImageGetList = Empty;
export type FwuImageRemove = FwuImageId;
export type FwuImageRemoveCompleted = FwuImageId;
export type FwuImageRemoveError = Error;
export type FwuImageRemoved = FwuImageId;
export type FwuStart = DeviceIds;
export type FwuStartCompleted = DeviceIds;
export type FwuStartError = Error;
export type FwuUpdateableGetList = Empty;
export type GetSystemState = Empty;
export type GetTime = Empty;
export type MissionCenterGet = Empty;
export type MissionCenterSet = MissionCenter;
export type MissionCenterSetCompleted = Empty;
export type OriginFilterAddCompleted = OriginFilterId;
export type OriginFilterAddError = Error;
export type OriginFilterAdded = OriginFilter;
export type OriginFilterGetList = Empty;
export type OriginFilterRemove = OriginFilterId;
export type OriginFilterRemoveCompleted = OriginFilterId;
export type OriginFilterRemoveError = Error;
export type OriginFilterRemoved = OriginFilterId;
export type OriginFilterUpdate = OriginFilter;
export type OriginFilterUpdateCompleted = OriginFilterId;
export type OriginFilterUpdateError = Error;
export type OriginFilterUpdated = OriginFilter;
export type PtzDeviceSetCompleted = DeviceId;
export type PtzDeviceSetError = Error;
export type PtzDeviceUpdate = PtzDeviceInfo;
export type PtzFollowGetList = Empty;
export type PtzFollowStartCompleted = PtzFollowId;
export type PtzFollowStartError = Error;
export type PtzFollowStarted = PtzFollow;
export type PtzFollowStop = PtzFollowId;
export type PtzFollowStopCompleted = PtzFollowId;
export type PtzFollowStopError = Error;
export type PtzFollowStopped = PtzFollow;
export type PtzGetDeviceList = Empty;
export type PtzMoveAbsCompleted = DeviceId;
export type PtzMoveAbsError = Error;
export type PtzSetVelocityCompleted = DeviceId;
export type PtzSetVelocityError = Error;
export type RfRecordClearList = Empty;
export type RfRecordClearListCompleted = Empty;
export type RfRecordGetList = Empty;
export type RfRecordSnapshotStart = DeviceId;
export type RfRecordSnapshotStartCompleted = DeviceId;
export type RfRecordSnapshotStartError = DeviceDeviceIdError;
export type RfRecordThreatsConfigure = RfRecordThreatsConfig;
export type RfRecordThreatsConfigureCompleted = Empty;
export type RfRecordThreatsConfigureError = Error;
export type RfRecordThreatsGetConfig = Empty;
export type SapientConfigureCompleted = Empty;
export type SapientConfigureError = Error;
export type SapientGetConfiguration = Empty;
export type SapientNodeGetList = Empty;
export type SapientNodeUpdated = SapientNode;
export type SystemLogGetList = Empty;
export type TakConfigureCompleted = Empty;
export type TakConfigureError = Error;
export type TakGetConfiguration = Empty;
export type TakTransportGetList = Empty;
export type TakTransportUpdated = TakTransport;
export type ThreatTypeGetList = Empty;
export type ThreatTypeMute = ThreatType;
export type ThreatTypeMuteCompleted = ThreatType;
export type ThreatTypeMuteError = Error;
export type ThreatTypeUnMute = ThreatType;
export type ThreatTypeUnMuteCompleted = ThreatType;
export type ThreatTypeUnMuteError = Error;
export type Timeout = Empty;
export type UthreatConfiguration = UthreatConfig;
export type UthreatConfigure = UthreatConfig;
export type UthreatConfigureCompleted = UthreatConfig;
export type UthreatConfigureError = Error;
export type UthreatGetConfiguration = Empty;
export type UthreatGetHistory = TimeInterval;
export type UthreatGetHistoryDataError = Error;
export type UthreatGetHistoryError = Error;
export type UthreatSetMuteCompleted = UthreatSetMute;
export type UthreatSetMuteError = Error;
export type VmsSdpInitError = Error;
export type VmsStreamGetList = Empty;
declare const emptyObjectSymbol: unique symbol;
export type Empty = {
    [emptyObjectSymbol]?: never;
};
export * from './argosApiManual';
export declare enum API {
    ALARM_STARTED = "alarmStarted",
    ALARM_STOPPED = "alarmStopped",
    ALARM_UPDATED = "alarmUpdated",
    ALARM_ZONE_ADD = "alarmZoneAdd",
    ALARM_ZONE_ADD_COMPLETED = "alarmZoneAddCompleted",
    ALARM_ZONE_ADD_ERROR = "alarmZoneAddError",
    ALARM_ZONE_ADDED = "alarmZoneAdded",
    ALARM_ZONE_GET_LIST = "alarmZoneGetList",
    ALARM_ZONE_LIST = "alarmZoneList",
    ALARM_ZONE_REMOVE = "alarmZoneRemove",
    ALARM_ZONE_REMOVE_COMPLETED = "alarmZoneRemoveCompleted",
    ALARM_ZONE_REMOVE_ERROR = "alarmZoneRemoveError",
    ALARM_ZONE_REMOVED = "alarmZoneRemoved",
    ALARM_ZONE_UPDATE = "alarmZoneUpdate",
    ALARM_ZONE_UPDATE_COMPLETED = "alarmZoneUpdateCompleted",
    ALARM_ZONE_UPDATE_ERROR = "alarmZoneUpdateError",
    ALARM_ZONE_UPDATED = "alarmZoneUpdated",
    API_ERROR = "apiError",
    COMPOSITE_DEVICE_ADD = "compositeDeviceAdd",
    COMPOSITE_DEVICE_ADD_COMPLETED = "compositeDeviceAddCompleted",
    COMPOSITE_DEVICE_ADD_ERROR = "compositeDeviceAddError",
    DEVICE_ADD = "deviceAdd",
    DEVICE_ADD_COMPLETED = "deviceAddCompleted",
    DEVICE_ADD_ERROR = "deviceAddError",
    DEVICE_ADDED = "deviceAdded",
    DEVICE_CALIBRATION_START = "deviceCalibrationStart",
    DEVICE_CALIBRATION_START_COMPLETED = "deviceCalibrationStartCompleted",
    DEVICE_CALIBRATION_START_ERROR = "deviceCalibrationStartError",
    DEVICE_GET_LIST = "deviceGetList",
    DEVICE_GET_LOCATIONS = "deviceGetLocations",
    DEVICE_GET_MISCELLANEOUS = "deviceGetMiscellaneous",
    DEVICE_LIST = "deviceList",
    DEVICE_LOCATION_CHANGE = "deviceLocationChange",
    DEVICE_LOCATION_CHANGE_COMPLETED = "deviceLocationChangeCompleted",
    DEVICE_LOCATION_CHANGE_ERROR = "deviceLocationChangeError",
    DEVICE_LOCATION_CHANGED = "deviceLocationChanged",
    DEVICE_LOCATIONS = "deviceLocations",
    DEVICE_MISCELLANEOUS = "deviceMiscellaneous",
    DEVICE_MISCELLANEOUS_CHANGE = "deviceMiscellaneousChange",
    DEVICE_MISCELLANEOUS_CHANGE_COMPLETED = "deviceMiscellaneousChangeCompleted",
    DEVICE_MISCELLANEOUS_CHANGE_ERROR = "deviceMiscellaneousChangeError",
    DEVICE_MISCELLANEOUS_CHANGED = "deviceMiscellaneousChanged",
    DEVICE_MOUNT = "deviceMount",
    DEVICE_MOUNT_COMPLETED = "deviceMountCompleted",
    DEVICE_MOUNT_ERROR = "deviceMountError",
    DEVICE_REMOVE = "deviceRemove",
    DEVICE_REMOVE_COMPLETED = "deviceRemoveCompleted",
    DEVICE_REMOVE_ERROR = "deviceRemoveError",
    DEVICE_REMOVED = "deviceRemoved",
    DEVICE_UNMOUNT = "deviceUnmount",
    DEVICE_UNMOUNT_COMPLETED = "deviceUnmountCompleted",
    DEVICE_UNMOUNT_ERROR = "deviceUnmountError",
    DEVICE_UPDATED = "deviceUpdated",
    ECM_CONFIGURATION = "ecmConfiguration",
    ECM_CONFIGURE = "ecmConfigure",
    ECM_CONFIGURE_COMPLETED = "ecmConfigureCompleted",
    ECM_CONFIGURE_ERROR = "ecmConfigureError",
    ECM_GET_CONFIGURATION = "ecmGetConfiguration",
    ECM_GET_HISTORY = "ecmGetHistory",
    ECM_GET_STATE = "ecmGetState",
    ECM_HISTORY = "ecmHistory",
    ECM_START = "ecmStart",
    ECM_START_COMPLETED = "ecmStartCompleted",
    ECM_START_ERROR = "ecmStartError",
    ECM_STATE = "ecmState",
    ECM_STOP = "ecmStop",
    ECM_STOP_COMPLETED = "ecmStopCompleted",
    ECM_STOP_ERROR = "ecmStopError",
    ECM_UPDATED = "ecmUpdated",
    FEATURE_GET_LIST = "featureGetList",
    FEATURE_LIST = "featureList",
    FWU_IMAGE_ADD = "fwuImageAdd",
    FWU_IMAGE_ADD_COMPLETED = "fwuImageAddCompleted",
    FWU_IMAGE_ADD_ERROR = "fwuImageAddError",
    FWU_IMAGE_ADDED = "fwuImageAdded",
    FWU_IMAGE_GET_LIST = "fwuImageGetList",
    FWU_IMAGE_LIST = "fwuImageList",
    FWU_IMAGE_REMOVE = "fwuImageRemove",
    FWU_IMAGE_REMOVE_COMPLETED = "fwuImageRemoveCompleted",
    FWU_IMAGE_REMOVE_ERROR = "fwuImageRemoveError",
    FWU_IMAGE_REMOVED = "fwuImageRemoved",
    FWU_START = "fwuStart",
    FWU_START_COMPLETED = "fwuStartCompleted",
    FWU_START_ERROR = "fwuStartError",
    FWU_UPDATEABLE_GET_LIST = "fwuUpdateableGetList",
    FWU_UPDATEABLE_LIST = "fwuUpdateableList",
    GET_SYSTEM_STATE = "getSystemState",
    GET_TIME = "getTime",
    MISSION_CENTER = "missionCenter",
    MISSION_CENTER_GET = "missionCenterGet",
    MISSION_CENTER_SET = "missionCenterSet",
    MISSION_CENTER_SET_COMPLETED = "missionCenterSetCompleted",
    ORIGIN_FILTER_ADD = "originFilterAdd",
    ORIGIN_FILTER_ADD_COMPLETED = "originFilterAddCompleted",
    ORIGIN_FILTER_ADD_ERROR = "originFilterAddError",
    ORIGIN_FILTER_ADDED = "originFilterAdded",
    ORIGIN_FILTER_GET_LIST = "originFilterGetList",
    ORIGIN_FILTER_LIST = "originFilterList",
    ORIGIN_FILTER_REMOVE = "originFilterRemove",
    ORIGIN_FILTER_REMOVE_COMPLETED = "originFilterRemoveCompleted",
    ORIGIN_FILTER_REMOVE_ERROR = "originFilterRemoveError",
    ORIGIN_FILTER_REMOVED = "originFilterRemoved",
    ORIGIN_FILTER_UPDATE = "originFilterUpdate",
    ORIGIN_FILTER_UPDATE_COMPLETED = "originFilterUpdateCompleted",
    ORIGIN_FILTER_UPDATE_ERROR = "originFilterUpdateError",
    ORIGIN_FILTER_UPDATED = "originFilterUpdated",
    PTZ_DEVICE_INFO = "ptzDeviceInfo",
    PTZ_DEVICE_LIST = "ptzDeviceList",
    PTZ_DEVICE_SET = "ptzDeviceSet",
    PTZ_DEVICE_SET_COMPLETED = "ptzDeviceSetCompleted",
    PTZ_DEVICE_SET_ERROR = "ptzDeviceSetError",
    PTZ_DEVICE_UPDATE = "ptzDeviceUpdate",
    PTZ_FOLLOW_GET_LIST = "ptzFollowGetList",
    PTZ_FOLLOW_LIST = "ptzFollowList",
    PTZ_FOLLOW_START = "ptzFollowStart",
    PTZ_FOLLOW_START_COMPLETED = "ptzFollowStartCompleted",
    PTZ_FOLLOW_START_ERROR = "ptzFollowStartError",
    PTZ_FOLLOW_STARTED = "ptzFollowStarted",
    PTZ_FOLLOW_STOP = "ptzFollowStop",
    PTZ_FOLLOW_STOP_COMPLETED = "ptzFollowStopCompleted",
    PTZ_FOLLOW_STOP_ERROR = "ptzFollowStopError",
    PTZ_FOLLOW_STOPPED = "ptzFollowStopped",
    PTZ_GET_DEVICE_LIST = "ptzGetDeviceList",
    PTZ_MOVE_ABS = "ptzMoveAbs",
    PTZ_MOVE_ABS_COMPLETED = "ptzMoveAbsCompleted",
    PTZ_MOVE_ABS_ERROR = "ptzMoveAbsError",
    PTZ_SET_VELOCITY = "ptzSetVelocity",
    PTZ_SET_VELOCITY_COMPLETED = "ptzSetVelocityCompleted",
    PTZ_SET_VELOCITY_ERROR = "ptzSetVelocityError",
    RF_GEO_THREAT_SIMULATION_RESULT = "rfGeoThreatSimulationResult",
    RF_GEO_THREAT_SIMULATION_START = "rfGeoThreatSimulationStart",
    RF_GEO_THREAT_SIMULATION_START_COMPLETED = "rfGeoThreatSimulationStartCompleted",
    RF_GEO_THREAT_SIMULATION_START_ERROR = "rfGeoThreatSimulationStartError",
    RF_RECORD_CLEAR_LIST = "rfRecordClearList",
    RF_RECORD_CLEAR_LIST_COMPLETED = "rfRecordClearListCompleted",
    RF_RECORD_GET_LIST = "rfRecordGetList",
    RF_RECORD_LIST = "rfRecordList",
    RF_RECORD_SNAPSHOT_START = "rfRecordSnapshotStart",
    RF_RECORD_SNAPSHOT_START_COMPLETED = "rfRecordSnapshotStartCompleted",
    RF_RECORD_SNAPSHOT_START_ERROR = "rfRecordSnapshotStartError",
    RF_RECORD_THREATS_CONFIG = "rfRecordThreatsConfig",
    RF_RECORD_THREATS_CONFIGURE = "rfRecordThreatsConfigure",
    RF_RECORD_THREATS_CONFIGURE_COMPLETED = "rfRecordThreatsConfigureCompleted",
    RF_RECORD_THREATS_CONFIGURE_ERROR = "rfRecordThreatsConfigureError",
    RF_RECORD_THREATS_GET_CONFIG = "rfRecordThreatsGetConfig",
    SAPIENT_CONFIGURATION = "sapientConfiguration",
    SAPIENT_CONFIGURE = "sapientConfigure",
    SAPIENT_CONFIGURE_COMPLETED = "sapientConfigureCompleted",
    SAPIENT_CONFIGURE_ERROR = "sapientConfigureError",
    SAPIENT_GET_CONFIGURATION = "sapientGetConfiguration",
    SAPIENT_NODE_GET_LIST = "sapientNodeGetList",
    SAPIENT_NODE_LIST = "sapientNodeList",
    SAPIENT_NODE_UPDATED = "sapientNodeUpdated",
    SYSTEM_LOG = "systemLog",
    SYSTEM_LOG_GET_LIST = "systemLogGetList",
    SYSTEM_LOG_LIST = "systemLogList",
    SYSTEM_STATE = "systemState",
    TAK_CONFIGURATION = "takConfiguration",
    TAK_CONFIGURE = "takConfigure",
    TAK_CONFIGURE_COMPLETED = "takConfigureCompleted",
    TAK_CONFIGURE_ERROR = "takConfigureError",
    TAK_GET_CONFIGURATION = "takGetConfiguration",
    TAK_TRANSPORT_GET_LIST = "takTransportGetList",
    TAK_TRANSPORT_LIST = "takTransportList",
    TAK_TRANSPORT_UPDATED = "takTransportUpdated",
    THREAT_TYPE_GET_LIST = "threatTypeGetList",
    THREAT_TYPE_LIST = "threatTypeList",
    THREAT_TYPE_MUTE = "threatTypeMute",
    THREAT_TYPE_MUTE_COMPLETED = "threatTypeMuteCompleted",
    THREAT_TYPE_MUTE_ERROR = "threatTypeMuteError",
    THREAT_TYPE_UN_MUTE = "threatTypeUnMute",
    THREAT_TYPE_UN_MUTE_COMPLETED = "threatTypeUnMuteCompleted",
    THREAT_TYPE_UN_MUTE_ERROR = "threatTypeUnMuteError",
    TIME = "time",
    TIMEOUT = "timeout",
    UTHREAT = "uthreat",
    UTHREAT_CONFIGURATION = "uthreatConfiguration",
    UTHREAT_CONFIGURE = "uthreatConfigure",
    UTHREAT_CONFIGURE_COMPLETED = "uthreatConfigureCompleted",
    UTHREAT_CONFIGURE_ERROR = "uthreatConfigureError",
    UTHREAT_GET_CONFIGURATION = "uthreatGetConfiguration",
    UTHREAT_GET_HISTORY = "uthreatGetHistory",
    UTHREAT_GET_HISTORY_DATA = "uthreatGetHistoryData",
    UTHREAT_GET_HISTORY_DATA_ERROR = "uthreatGetHistoryDataError",
    UTHREAT_GET_HISTORY_ERROR = "uthreatGetHistoryError",
    UTHREAT_HISTORY = "uthreatHistory",
    UTHREAT_HISTORY_DATA = "uthreatHistoryData",
    UTHREAT_SET_MUTE = "uthreatSetMute",
    UTHREAT_SET_MUTE_COMPLETED = "uthreatSetMuteCompleted",
    UTHREAT_SET_MUTE_ERROR = "uthreatSetMuteError",
    VMS_SDP_INIT = "vmsSdpInit",
    VMS_SDP_INIT_COMPLETED = "vmsSdpInitCompleted",
    VMS_SDP_INIT_ERROR = "vmsSdpInitError",
    VMS_STREAM_GET_LIST = "vmsStreamGetList",
    VMS_STREAM_LIST = "vmsStreamList"
}
export type ArgosTypesMap = {
    [API.ALARM_STARTED]: AlarmStarted;
    [API.ALARM_STOPPED]: AlarmStopped;
    [API.ALARM_UPDATED]: AlarmUpdated;
    [API.ALARM_ZONE_ADD]: AlarmZoneAdd;
    [API.ALARM_ZONE_ADD_COMPLETED]: AlarmZoneAddCompleted;
    [API.ALARM_ZONE_ADD_ERROR]: AlarmZoneAddError;
    [API.ALARM_ZONE_ADDED]: AlarmZoneAdded;
    [API.ALARM_ZONE_GET_LIST]: AlarmZoneGetList;
    [API.ALARM_ZONE_LIST]: AlarmZoneList;
    [API.ALARM_ZONE_REMOVE]: AlarmZoneRemove;
    [API.ALARM_ZONE_REMOVE_COMPLETED]: AlarmZoneRemoveCompleted;
    [API.ALARM_ZONE_REMOVE_ERROR]: AlarmZoneRemoveError;
    [API.ALARM_ZONE_REMOVED]: AlarmZoneRemoved;
    [API.ALARM_ZONE_UPDATE]: AlarmZoneUpdate;
    [API.ALARM_ZONE_UPDATE_COMPLETED]: AlarmZoneUpdateCompleted;
    [API.ALARM_ZONE_UPDATE_ERROR]: AlarmZoneUpdateError;
    [API.ALARM_ZONE_UPDATED]: AlarmZoneUpdated;
    [API.API_ERROR]: ApiError;
    [API.COMPOSITE_DEVICE_ADD]: CompositeDeviceAdd;
    [API.COMPOSITE_DEVICE_ADD_COMPLETED]: CompositeDeviceAddCompleted;
    [API.COMPOSITE_DEVICE_ADD_ERROR]: CompositeDeviceAddError;
    [API.DEVICE_ADD]: DeviceAdd;
    [API.DEVICE_ADD_COMPLETED]: DeviceAddCompleted;
    [API.DEVICE_ADD_ERROR]: DeviceAddError;
    [API.DEVICE_ADDED]: DeviceAdded;
    [API.DEVICE_CALIBRATION_START]: DeviceCalibrationStart;
    [API.DEVICE_CALIBRATION_START_COMPLETED]: DeviceCalibrationStartCompleted;
    [API.DEVICE_CALIBRATION_START_ERROR]: DeviceCalibrationStartError;
    [API.DEVICE_GET_LIST]: DeviceGetList;
    [API.DEVICE_GET_LOCATIONS]: DeviceGetLocations;
    [API.DEVICE_GET_MISCELLANEOUS]: DeviceGetMiscellaneous;
    [API.DEVICE_LIST]: DeviceList;
    [API.DEVICE_LOCATION_CHANGE]: DeviceLocationChange;
    [API.DEVICE_LOCATION_CHANGE_COMPLETED]: DeviceLocationChangeCompleted;
    [API.DEVICE_LOCATION_CHANGE_ERROR]: DeviceLocationChangeError;
    [API.DEVICE_LOCATION_CHANGED]: DeviceLocationChanged;
    [API.DEVICE_LOCATIONS]: DeviceLocations;
    [API.DEVICE_MISCELLANEOUS]: DeviceMiscellaneous;
    [API.DEVICE_MISCELLANEOUS_CHANGE]: DeviceMiscellaneousChange;
    [API.DEVICE_MISCELLANEOUS_CHANGE_COMPLETED]: DeviceMiscellaneousChangeCompleted;
    [API.DEVICE_MISCELLANEOUS_CHANGE_ERROR]: DeviceMiscellaneousChangeError;
    [API.DEVICE_MISCELLANEOUS_CHANGED]: DeviceMiscellaneousChanged;
    [API.DEVICE_MOUNT]: DeviceMount;
    [API.DEVICE_MOUNT_COMPLETED]: DeviceMountCompleted;
    [API.DEVICE_MOUNT_ERROR]: DeviceMountError;
    [API.DEVICE_REMOVE]: DeviceRemove;
    [API.DEVICE_REMOVE_COMPLETED]: DeviceRemoveCompleted;
    [API.DEVICE_REMOVE_ERROR]: DeviceRemoveError;
    [API.DEVICE_REMOVED]: DeviceRemoved;
    [API.DEVICE_UNMOUNT]: DeviceUnmount;
    [API.DEVICE_UNMOUNT_COMPLETED]: DeviceUnmountCompleted;
    [API.DEVICE_UNMOUNT_ERROR]: DeviceUnmountError;
    [API.DEVICE_UPDATED]: DeviceUpdated;
    [API.ECM_CONFIGURATION]: EcmConfiguration;
    [API.ECM_CONFIGURE]: EcmConfigure;
    [API.ECM_CONFIGURE_COMPLETED]: EcmConfigureCompleted;
    [API.ECM_CONFIGURE_ERROR]: EcmConfigureError;
    [API.ECM_GET_CONFIGURATION]: EcmGetConfiguration;
    [API.ECM_GET_HISTORY]: EcmGetHistory;
    [API.ECM_GET_STATE]: EcmGetState;
    [API.ECM_HISTORY]: EcmHistory;
    [API.ECM_START]: EcmStart;
    [API.ECM_START_COMPLETED]: EcmStartCompleted;
    [API.ECM_START_ERROR]: EcmStartError;
    [API.ECM_STATE]: EcmState;
    [API.ECM_STOP]: EcmStop;
    [API.ECM_STOP_COMPLETED]: EcmStopCompleted;
    [API.ECM_STOP_ERROR]: EcmStopError;
    [API.ECM_UPDATED]: EcmUpdated;
    [API.FEATURE_GET_LIST]: FeatureGetList;
    [API.FEATURE_LIST]: FeatureList;
    [API.FWU_IMAGE_ADD]: FwuImageAdd;
    [API.FWU_IMAGE_ADD_COMPLETED]: FwuImageAddCompleted;
    [API.FWU_IMAGE_ADD_ERROR]: FwuImageAddError;
    [API.FWU_IMAGE_ADDED]: FwuImageAdded;
    [API.FWU_IMAGE_GET_LIST]: FwuImageGetList;
    [API.FWU_IMAGE_LIST]: FwuImageList;
    [API.FWU_IMAGE_REMOVE]: FwuImageRemove;
    [API.FWU_IMAGE_REMOVE_COMPLETED]: FwuImageRemoveCompleted;
    [API.FWU_IMAGE_REMOVE_ERROR]: FwuImageRemoveError;
    [API.FWU_IMAGE_REMOVED]: FwuImageRemoved;
    [API.FWU_START]: FwuStart;
    [API.FWU_START_COMPLETED]: FwuStartCompleted;
    [API.FWU_START_ERROR]: FwuStartError;
    [API.FWU_UPDATEABLE_GET_LIST]: FwuUpdateableGetList;
    [API.FWU_UPDATEABLE_LIST]: FwuUpdateableList;
    [API.GET_SYSTEM_STATE]: GetSystemState;
    [API.GET_TIME]: GetTime;
    [API.MISSION_CENTER]: MissionCenter;
    [API.MISSION_CENTER_GET]: MissionCenterGet;
    [API.MISSION_CENTER_SET]: MissionCenterSet;
    [API.MISSION_CENTER_SET_COMPLETED]: MissionCenterSetCompleted;
    [API.ORIGIN_FILTER_ADD]: OriginFilterAdd;
    [API.ORIGIN_FILTER_ADD_COMPLETED]: OriginFilterAddCompleted;
    [API.ORIGIN_FILTER_ADD_ERROR]: OriginFilterAddError;
    [API.ORIGIN_FILTER_ADDED]: OriginFilterAdded;
    [API.ORIGIN_FILTER_GET_LIST]: OriginFilterGetList;
    [API.ORIGIN_FILTER_LIST]: OriginFilterList;
    [API.ORIGIN_FILTER_REMOVE]: OriginFilterRemove;
    [API.ORIGIN_FILTER_REMOVE_COMPLETED]: OriginFilterRemoveCompleted;
    [API.ORIGIN_FILTER_REMOVE_ERROR]: OriginFilterRemoveError;
    [API.ORIGIN_FILTER_REMOVED]: OriginFilterRemoved;
    [API.ORIGIN_FILTER_UPDATE]: OriginFilterUpdate;
    [API.ORIGIN_FILTER_UPDATE_COMPLETED]: OriginFilterUpdateCompleted;
    [API.ORIGIN_FILTER_UPDATE_ERROR]: OriginFilterUpdateError;
    [API.ORIGIN_FILTER_UPDATED]: OriginFilterUpdated;
    [API.PTZ_DEVICE_INFO]: PtzDeviceInfo;
    [API.PTZ_DEVICE_LIST]: PtzDeviceList;
    [API.PTZ_DEVICE_SET]: PtzDeviceSet;
    [API.PTZ_DEVICE_SET_COMPLETED]: PtzDeviceSetCompleted;
    [API.PTZ_DEVICE_SET_ERROR]: PtzDeviceSetError;
    [API.PTZ_DEVICE_UPDATE]: PtzDeviceUpdate;
    [API.PTZ_FOLLOW_GET_LIST]: PtzFollowGetList;
    [API.PTZ_FOLLOW_LIST]: PtzFollowList;
    [API.PTZ_FOLLOW_START]: PtzFollowStart;
    [API.PTZ_FOLLOW_START_COMPLETED]: PtzFollowStartCompleted;
    [API.PTZ_FOLLOW_START_ERROR]: PtzFollowStartError;
    [API.PTZ_FOLLOW_STARTED]: PtzFollowStarted;
    [API.PTZ_FOLLOW_STOP]: PtzFollowStop;
    [API.PTZ_FOLLOW_STOP_COMPLETED]: PtzFollowStopCompleted;
    [API.PTZ_FOLLOW_STOP_ERROR]: PtzFollowStopError;
    [API.PTZ_FOLLOW_STOPPED]: PtzFollowStopped;
    [API.PTZ_GET_DEVICE_LIST]: PtzGetDeviceList;
    [API.PTZ_MOVE_ABS]: PtzMoveAbs;
    [API.PTZ_MOVE_ABS_COMPLETED]: PtzMoveAbsCompleted;
    [API.PTZ_MOVE_ABS_ERROR]: PtzMoveAbsError;
    [API.PTZ_SET_VELOCITY]: PtzSetVelocity;
    [API.PTZ_SET_VELOCITY_COMPLETED]: PtzSetVelocityCompleted;
    [API.PTZ_SET_VELOCITY_ERROR]: PtzSetVelocityError;
    [API.RF_GEO_THREAT_SIMULATION_RESULT]: RfGeoThreatSimulationResult;
    [API.RF_GEO_THREAT_SIMULATION_START]: RfGeoThreatSimulationStart;
    [API.RF_GEO_THREAT_SIMULATION_START_COMPLETED]: RfGeoThreatSimulationStartCompleted;
    [API.RF_GEO_THREAT_SIMULATION_START_ERROR]: RfGeoThreatSimulationStartError;
    [API.RF_RECORD_CLEAR_LIST]: RfRecordClearList;
    [API.RF_RECORD_CLEAR_LIST_COMPLETED]: RfRecordClearListCompleted;
    [API.RF_RECORD_GET_LIST]: RfRecordGetList;
    [API.RF_RECORD_LIST]: RfRecordList;
    [API.RF_RECORD_SNAPSHOT_START]: RfRecordSnapshotStart;
    [API.RF_RECORD_SNAPSHOT_START_COMPLETED]: RfRecordSnapshotStartCompleted;
    [API.RF_RECORD_SNAPSHOT_START_ERROR]: RfRecordSnapshotStartError;
    [API.RF_RECORD_THREATS_CONFIG]: RfRecordThreatsConfig;
    [API.RF_RECORD_THREATS_CONFIGURE]: RfRecordThreatsConfigure;
    [API.RF_RECORD_THREATS_CONFIGURE_COMPLETED]: RfRecordThreatsConfigureCompleted;
    [API.RF_RECORD_THREATS_CONFIGURE_ERROR]: RfRecordThreatsConfigureError;
    [API.RF_RECORD_THREATS_GET_CONFIG]: RfRecordThreatsGetConfig;
    [API.SAPIENT_CONFIGURATION]: SapientConfiguration;
    [API.SAPIENT_CONFIGURE]: SapientConfigure;
    [API.SAPIENT_CONFIGURE_COMPLETED]: SapientConfigureCompleted;
    [API.SAPIENT_CONFIGURE_ERROR]: SapientConfigureError;
    [API.SAPIENT_GET_CONFIGURATION]: SapientGetConfiguration;
    [API.SAPIENT_NODE_GET_LIST]: SapientNodeGetList;
    [API.SAPIENT_NODE_LIST]: SapientNodeList;
    [API.SAPIENT_NODE_UPDATED]: SapientNodeUpdated;
    [API.SYSTEM_LOG]: SystemLog;
    [API.SYSTEM_LOG_GET_LIST]: SystemLogGetList;
    [API.SYSTEM_LOG_LIST]: SystemLogList;
    [API.SYSTEM_STATE]: SystemState;
    [API.TAK_CONFIGURATION]: TakConfiguration;
    [API.TAK_CONFIGURE]: TakConfigure;
    [API.TAK_CONFIGURE_COMPLETED]: TakConfigureCompleted;
    [API.TAK_CONFIGURE_ERROR]: TakConfigureError;
    [API.TAK_GET_CONFIGURATION]: TakGetConfiguration;
    [API.TAK_TRANSPORT_GET_LIST]: TakTransportGetList;
    [API.TAK_TRANSPORT_LIST]: TakTransportList;
    [API.TAK_TRANSPORT_UPDATED]: TakTransportUpdated;
    [API.THREAT_TYPE_GET_LIST]: ThreatTypeGetList;
    [API.THREAT_TYPE_LIST]: ThreatTypeList;
    [API.THREAT_TYPE_MUTE]: ThreatTypeMute;
    [API.THREAT_TYPE_MUTE_COMPLETED]: ThreatTypeMuteCompleted;
    [API.THREAT_TYPE_MUTE_ERROR]: ThreatTypeMuteError;
    [API.THREAT_TYPE_UN_MUTE]: ThreatTypeUnMute;
    [API.THREAT_TYPE_UN_MUTE_COMPLETED]: ThreatTypeUnMuteCompleted;
    [API.THREAT_TYPE_UN_MUTE_ERROR]: ThreatTypeUnMuteError;
    [API.TIME]: Time;
    [API.TIMEOUT]: Timeout;
    [API.UTHREAT]: Uthreat;
    [API.UTHREAT_CONFIGURATION]: UthreatConfiguration;
    [API.UTHREAT_CONFIGURE]: UthreatConfigure;
    [API.UTHREAT_CONFIGURE_COMPLETED]: UthreatConfigureCompleted;
    [API.UTHREAT_CONFIGURE_ERROR]: UthreatConfigureError;
    [API.UTHREAT_GET_CONFIGURATION]: UthreatGetConfiguration;
    [API.UTHREAT_GET_HISTORY]: UthreatGetHistory;
    [API.UTHREAT_GET_HISTORY_DATA]: UthreatGetHistoryData;
    [API.UTHREAT_GET_HISTORY_DATA_ERROR]: UthreatGetHistoryDataError;
    [API.UTHREAT_GET_HISTORY_ERROR]: UthreatGetHistoryError;
    [API.UTHREAT_HISTORY]: UthreatHistory;
    [API.UTHREAT_HISTORY_DATA]: UthreatHistoryData;
    [API.UTHREAT_SET_MUTE]: UthreatSetMute;
    [API.UTHREAT_SET_MUTE_COMPLETED]: UthreatSetMuteCompleted;
    [API.UTHREAT_SET_MUTE_ERROR]: UthreatSetMuteError;
    [API.VMS_SDP_INIT]: VmsSdpInit;
    [API.VMS_SDP_INIT_COMPLETED]: VmsSdpInitCompleted;
    [API.VMS_SDP_INIT_ERROR]: VmsSdpInitError;
    [API.VMS_STREAM_GET_LIST]: VmsStreamGetList;
    [API.VMS_STREAM_LIST]: VmsStreamList;
};
