/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export type Alarm = {
    /**
     * Unique id of the alarm zone.
     */
    alarmZoneId: string;
    /**
     * Visual alarm level of the alarm zone.
     */
    visualAlarmLevel: number;
    /**
     * Audio alarm level of the alarm zone.
     */
    audioAlarmLevel: number;
    /**
     * Unique id for this alarm
     */
    alarmId: string;
    /**
     * List of uthreats currently contributing to this alarm (breaching alarm zone with alarmZoneId)
     */
    uthreatIds: string[];
    /**
     * Timestamp of when this alarm was started
     */
    createdTimeStamp: string;
    /**
     * Timestamp of when this alarm was updated
     */
    updatedTimeStamp: string;
    /**
     * Timestamp of when this alarm was stopped
     */
    stoppedTimeStamp?: string;
};
