/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export type AlarmZone = AlarmZonePolygon | AlarmZoneCircle;
/**
 * List of alarm zones.
 */
export type AlarmZoneList = AlarmZone[];
export type AlarmZonePolygon = {
    /**
     * Unique id of the alarm zone.
     */
    alarmZoneId: string;
    /**
     * Color of the alarm zone.
     */
    color: string;
    /**
     * Name of the alarm zone.
     */
    name: string;
    /**
     * Order (layer) of the alarm zone.
     */
    order: number;
    /**
     * Switch for (de)activating the alarm zone.
     */
    isActive: boolean;
    /**
     * Visual alarm level of the alarm zone.
     */
    visualAlarmLevel: number;
    /**
     * Audio alarm level of the alarm zone.
     */
    audioAlarmLevel: number;
    /**
     * Polygon defining the alarm zone.
     */
    polygon: {
        /**
         * Latitude of point in polygon.
         */
        lat: number;
        /**
         * Longitude of point in polygon.
         */
        lon: number;
    }[];
};
export type AlarmZoneCircle = {
    /**
     * Unique id of the alarm zone.
     */
    alarmZoneId: string;
    /**
     * Color of the alarm zone.
     */
    color: string;
    /**
     * Name of the alarm zone.
     */
    name: string;
    /**
     * Order (layer) of the alarm zone.
     */
    order: number;
    /**
     * Switch for (de)activating the alarm zone.
     */
    isActive: boolean;
    /**
     * Visual alarm level of the alarm zone.
     */
    visualAlarmLevel: number;
    /**
     * Audio alarm level of the alarm zone.
     */
    audioAlarmLevel: number;
    /**
     * Circle defining the alarm zone..
     */
    circle: {
        /**
         * Latitude of the circle center.
         */
        lat: number;
        /**
         * Longitude of the circle center.
         */
        lon: number;
        /**
         * radius of the circle in meters.
         */
        radiusInMeters: number;
    };
};
