/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
/**
 * Description of the API error
 */
export type Error = "invalidEvent" | "invalidResponseId" | "schemaViolation";
export type ApiError = {
    error: Error;
    originalMessage: OriginalMessage;
    /**
     * Original event causing the error
     */
    originalEvent: string;
    /**
     * Optional additional error information
     */
    info?: string;
};
/**
 * Copy of the original message causing the error
 */
export type OriginalMessage = {
    [k: string]: unknown;
};
