/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
/**
 * Device types tells what kind of device it is and with that what kind of attributes and abilities is available - must always be used in combination with deviceVersion and if composite with the sub/composite devices found under the devices list
 */
export type DeviceType = "composite" | "duo" | "trio" | "quad" | "penta" | "hexa" | "hepta" | "echoguardQuad" | "groundawareTrio" | "echoshieldQuad";
/**
 * The version of the composite template will typically be the version of the devices used to create the composite. If deviceType is "composite" deviceVersion is ignored.
 */
export type DeviceVersion = number;
/**
 * A unique device serialnumber. Will be auto-generated if not supplied.
 */
export type DeviceSerialnumber = string | null;
/**
 * JSON schema for the compositeDeviceAdd event
 */
export type CompositeDeviceAdd = {
    deviceType: DeviceType;
    deviceVersion: DeviceVersion;
    /**
     * Only used with deviceType=composite: Used for miscellaneous data fields productName and deviceName.
     */
    productName?: string;
    devices: {
        deviceId: string;
        heading: number;
        /**
         * DEPRECATED. Do not add this property. Will be disallowed in the future!
         */
        hasOmniAntenna?: boolean;
    }[];
    /**
     * DEPRECATED. Do not add this property. Will be disallowed in the future!
     */
    devicesCount?: number;
    /**
     * DEPRECATED. Do not add this property. Will be disallowed in the future!
     */
    deviceParentId?: string | null;
    deviceSerialNumber?: DeviceSerialnumber;
};
