/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export type DeviceLocation = DeviceGeolocation;
export type DeviceLocationList = {
    deviceId: string;
    deviceLocations: DeviceLocation[];
};
export type DeviceGeolocation = {
    /**
     * The device id
     */
    deviceId: string;
    deviceLocationType: "deviceGeolocation";
    /**
     * Decimal latitude value
     */
    deviceLocationLatitude: number;
    /**
     * Decimal longitude value
     */
    deviceLocationLongitude: number;
    /**
     * Heading relative to true north in degrees
     */
    deviceLocationHeading: number;
    /**
     * Height relative to choosen reference in meters
     */
    deviceLocationHeight: number;
    /**
     * Pitch in degrees for which the device is mounted
     */
    deviceLocationPitch?: number;
    /**
     * Roll in degrees for which the device is mounted
     */
    deviceLocationRoll?: number;
    /**
     * Device id of parent if part of a composite device
     */
    deviceParentId?: string | null;
};
