/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
/**
 * A unique device serialnumber either received from the device itself if autodetected, if manually created from the input received.
 */
export type DeviceSerialnumber = string;
/**
 * Device types tells what kind of device it is and with that what kind of attributes and abilities is available - must always be used in combination with deviceVersion and if composite with the sub/composite devices found under the devices list
 */
export type DeviceType = "blackbird" | "jaegar" | "dobermann" | "dobermann360" | "dobermann_dual" | "duo" | "echoguard" | "gps" | "groundaware" | "hepta" | "hexa" | "penta" | "pentaDM1xx" | "pentaWD2xx" | "quad" | "quadWD2xx" | "trio" | "wd200" | "wingman" | "wl1" | "wm200" | "wolfpack" | "onvif" | "skyeye" | "blackbird5k" | "echoguardQuad" | "groundawareTrio" | "aps" | "ring" | "xenta" | "echoshield" | "echoshieldQuad" | "visionflex";
/**
 * Defines the version of the individual devices and the capabilities attached to the specific device type version
 */
export type DeviceVersion = number;
/**
 * Defines the devices IP address either received when the devices was discovered or when the device was manually created.
 */
export type DeviceIP = string;
/**
 * Defines the devices MAC address either received when the devices was discovered or when the device was manually created.
 */
export type DeviceMAC = string | null;
export type DeviceAdd = {
    deviceSerialNumber?: DeviceSerialnumber;
    deviceType: DeviceType;
    deviceVersion: DeviceVersion;
    deviceIP: DeviceIP;
    deviceMac: DeviceMAC;
};
