/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export type DeviceLocation = DeviceGeolocation;
export type DeviceGeolocation = {
    /**
     * The device id
     */
    deviceId: string;
    deviceLocationType: "deviceGeolocation";
    /**
     * Decimal latitude value
     */
    deviceLocationLatitude: number;
    /**
     * Decimal longitude value
     */
    deviceLocationLongitude: number;
    /**
     * Heading relative to true north in degrees
     */
    deviceLocationHeading: number;
    /**
     * If mission center is configured, this is set to the x coordinate (meters) of the device relative to the mission center. Update of mission center will not trigger location update messages. Cannot be set directly, only through deviceLocationLatitude/Longitude.
     */
    deviceLocationX?: number;
    /**
     * If mission center is configured, this is set to the y coordinate (meters) of the device relative to the mission center. Update of mission center will not trigger location update messages. Cannot be set directly, only through deviceLocationLatitude/Longitude.
     */
    deviceLocationY?: number;
    /**
     * Height relative to choosen reference in meters
     */
    deviceLocationHeight: number;
    /**
     * Pitch in degrees for which the device is mounted
     */
    deviceLocationPitch?: number;
    /**
     * Roll in degrees for which the device is mounted
     */
    deviceLocationRoll?: number;
    /**
     * Device id of parent if part of a composite device
     */
    deviceParentId?: string | null;
};
