/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
/**
 * A unique device identification, generated automatically from the system - will change if a device is removed entirely from the system and then added again
 */
export type DeviceIdentification = string;
/**
 * A description of what error has occurred and e.g. any identification needed in relation to the error.
 */
export type ErrorInformationDeviceIdentification = string;
export type DeviceDeviceIdError = {
    deviceId: DeviceIdentification;
    errorInfo: ErrorInformationDeviceIdentification;
};
