/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export type DeviceIdentification = string | null;
/**
 * Information about the frequency of an effector/detector.
 */
export type FrequencyBand = "433" | "900" | "1G2" | "2G4" | "5G2" | "5G8" | "GNSS";
export type EcmState = {
    deviceId: string;
    deviceParentId?: DeviceIdentification;
    activeFrequencyBands?: FrequencyBand[];
    deviceDetails?: {
        [k: string]: unknown;
    };
    /**
     * UTC time in ISO8601 format
     */
    timestamp?: string;
    /**
     * Timeout (seconds) of auto jamming. Set when deviceId ='auto'
     */
    timeout?: number;
};
