/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
/**
 * Features of the backend.
 */
export type Feature = "radarDevices" | "rfGeoThreatCoverageSim" | "frontendTimingGraph" | "frontendDevMode" | "sapientIntegration" | "vehicleMode" | "segmentRecording";
export type FeatureList = Feature[];
