/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export type MissionCenter = {
    /**
     * Defines the geographical latitude with up to 6 decimals. null if not set.
     */
    latitude: number | null;
    /**
     * Defines the geographical longitude with up to 6 decimals. null if not set.
     */
    longitude: number | null;
};
