/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export type PtzDeviceSet = {
    /**
     * The device id
     */
    deviceId: string;
    /**
     * If camera tracking can be assigned to the sub devices this sets chosen sub device.
     */
    trackingSubDevice?: number;
    /**
     * Set camera tracking state
     */
    tracking?: "disabled" | "acquire" | "track";
    /**
     * Set or disable timeout. See PtzDeviceInfo.
     */
    resetOrientationTimeout?: number | null;
};
