/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export type PtzDeviceSet = {
    /**
     * The device id. For PTZ devices in composites, this is the id of the child (PTZ) device.
     */
    deviceId: string;
    /**
     * If camera tracking can be assigned to the sub devices this sets chosen sub device.
     */
    trackingSubDevice?: number;
    /**
     * Set camera tracking state. `acquire`: Start searching for threats in the video stream and track them if found. If ptzFollowStart is used, this should not be used also.
     */
    tracking?: "disabled" | "acquire";
    /**
     * Set or disable timeout. See PtzDeviceInfo.
     */
    resetOrientationTimeout?: number | null;
};
