/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
/**
 * Device ID of a PTZ device
 */
export type PTZFollowInstanceIdentication = string;
export type PtzFollowId = {
    ptzFollowId: PTZFollowInstanceIdentication;
};
