/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export type PtzFollowList = PtzFollow[];
export type PtzFollow = {
    /**
     * ID of the PTZ follow instance
     */
    ptzFollowId: string;
    /**
     * Device ID of the PTZ device used for following
     */
    deviceId: string;
    /**
     * uthreat ID of the threat that is followed. Present when following a threat
     */
    followUthreatId?: string;
    /**
     * Device ID of device that is followed (e.g. GPS). Present when following a device
     */
    followDeviceId?: string;
};
