/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
/**
 * Start following a device or a threat. Cameras with vision based tracking will start searching for the threat and take over the tracking if found.
 */
export type PtzFollowStart = {
    /**
     * Device ID of the PTZ device to use for following. For PTZ devices in composites, this is the id of the child (PTZ) device.
     */
    deviceId: string;
    /**
     * uthreat ID of threat to follow
     */
    followUthreatId?: string;
    /**
     * Device ID of device to follow (e.g. GPS)
     */
    followDeviceId?: string;
};
