/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export type PtzFollowStart = {
    /**
     * Device ID of the PTZ device to use for following
     */
    deviceId: string;
    /**
     * uthreat ID of threat to follow
     */
    followUthreatId?: string;
    /**
     * Device ID of device to follow (e.g. GPS)
     */
    followDeviceId?: string;
};
