/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export type PtzMoveAbs = PtzMoveAbsOrientation | PtzMoveAbsPosition;
/**
 * Device ID of a PTZ device
 */
export type DeviceIdentification = string;
/**
 * ID of a sub device of the PTZ device.
 */
export type SubDeviceIdentification = number;
/**
 * Device ID of a PTZ device
 */
export type DeviceIdentification1 = string;
/**
 * ID of a sub device of the PTZ device.
 */
export type SubDeviceIdentification1 = number;
export type PtzMoveAbsOrientation = {
    deviceId: DeviceIdentification;
    subDeviceId?: SubDeviceIdentification;
    orientation: TargetOrientationOfThePTZDevice;
};
/**
 * PTZ device will move to the specified orientation [deg]
 */
export type TargetOrientationOfThePTZDevice = {
    /**
     * Pan orientation [deg].
     */
    p?: number | "default";
    /**
     * Tilt orientation [deg].
     */
    t?: number | "default";
    /**
     * Zoom position.
     */
    z?: number | "default";
    /**
     * Focus [pct].
     */
    f?: number | "default";
    /**
     * Unit of zoom e.g. deg FOV or percentage of full range. Supported units are device dependent and both units may not be supported by all devices.
     */
    zUnits?: "deg" | "pct";
};
export type PtzMoveAbsPosition = {
    deviceId: DeviceIdentification1;
    subDeviceId?: SubDeviceIdentification1;
    position: GeographicalPositionPTZDeviceShouldPointTowards;
};
/**
 * PTZ device will move to the specified geographical position
 */
export type GeographicalPositionPTZDeviceShouldPointTowards = {
    /**
     * Defines the geographical latitude with up to 6 decimals.
     */
    latitude: number;
    /**
     * Defines the geographical longitude with up to 6 decimals.
     */
    longitude: number;
    /**
     * Defines the height with up to 6 decimals.
     */
    height?: number;
    /**
     * Zoom position.
     */
    zoom?: number;
    /**
     * Focus position.
     */
    focus?: number;
    /**
     * Unit of zoom e.g. deg FOV or percentage of full range.
     */
    zUnits?: "deg" | "pct";
};
