/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
/**
 * Device ID of a PTZ device
 */
export type DeviceIdentification = string;
/**
 * ID of a sub device of the PTZ device used for following
 */
export type SubDeviceIdentification = number;
/**
 * Specification of velocity unit for pan/tilt. See description of PtzDeviceInfo
 */
export type VelocityUnitOfPanTiltEGDegSOrPercentageOfFullVelocity = "deg/s" | "pct";
/**
 * Velocity of which the PTZ device should be moving
 */
export type PtzSetVelocity = {
    deviceId: DeviceIdentification;
    subDeviceId?: SubDeviceIdentification;
    /**
     * Pan velocity.
     */
    p?: number;
    /**
     * Tilt velocity.
     */
    t?: number;
    /**
     * Zoom velocity -1 - +1.
     */
    z?: number;
    /**
     * Focus velocity -1 - +1.
     */
    f?: number;
    ptUnits?: VelocityUnitOfPanTiltEGDegSOrPercentageOfFullVelocity;
};
