/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
/**
 * Velocity of which the PTZ device should be moving
 */
export type PtzSetVelocity = {
    /**
     * Device ID of a PTZ device
     */
    deviceId: string;
    /**
     * ID of a sub device of the PTZ device
     */
    subDeviceId?: number;
    /**
     * Pan velocity.
     */
    p?: number;
    /**
     * Tilt velocity.
     */
    t?: number;
    /**
     * Zoom velocity -1 - +1.
     */
    z?: number;
    /**
     * Focus velocity -1 - +1.
     */
    f?: number;
    /**
     * Specification of velocity unit for pan/tilt. See description of PtzDeviceInfo
     */
    ptUnits?: "deg/s" | "pct";
};
