/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
/**
 * Contains the results of a deployment simulation. Generally references to the x-dimension or axis is in metres and refers to the west-east direction (east is positive). Similarly for the y-dimension, where the north-direction is positive.
 */
export type RfGeoThreatSimulationResult = {
    /**
     * Unique simulation number from rfGeoThreatSimulationStart which initiated the simulation.
     */
    simulationNumber: number;
    /**
     * True if request simulation completed and results (the rest of this message) is valid.
     */
    valid: boolean;
    /**
     * Textual error message if valid is not true.
     */
    errorInfo: string;
    requestMsg: RfGeoThreatSimulationStart;
    /**
     * Contains parametric information about what is simulated.
     */
    resultParametrics: {
        /**
         * Number of simulation cells in X- and Y-directions.
         *
         * @minItems 2
         * @maxItems 2
         */
        numXY: [number, number];
        /**
         * Center coordinate [m] of lower left simulation cell.
         *
         * @minItems 2
         * @maxItems 2
         */
        lowerLeftXY: [number, number];
        /**
         * Center coordinate [m] of upper right simulation cell.
         *
         * @minItems 2
         * @maxItems 2
         */
        upperRightXY: [number, number];
    };
    /**
     * List of estimated precision in localization - each element of the list corresponds to a 2D-matrix (x, y). Starting from the top row and proceeding downwards.
     *
     * @minItems 0
     */
    estimatedPrecision: {
        /**
         * x-coordinate of first element
         */
        x0: number;
        /**
         * y-coordinate of first element
         */
        y0: number;
        /**
         * The estimated precision [m] or null if not able to estimate for that point. The first element has location (x0, y0) and subsequent elements increments the x-coordinate by the simulation resolution.
         */
        values: (number | null)[];
    }[];
    /**
     * List of directions and the maximum estimated range that the RF-sensors can detect in this direction. Use this to provide a maximum boundary of the deployment. The first value in the list is 0deg direction from origo (East) and continues counter-clockwise with an increment of <>
     */
    maxDetectionRangeBoundary: (null | number)[];
};
/**
 * Request a simulation to get estimated performance of an RF-sensor deployment. Currently the processing in the system will be stopped while a deployment is simulated. In the future this can be changed to support simultaneous operation and deployment-simulations.
 */
export type RfGeoThreatSimulationStart = {
    /**
     * Unique simulation number.
     */
    simulationNumber: number;
    /**
     * GNSS latitude, longitude [decimal degrees]of center of the simulation space.
     *
     * @minItems 2
     * @maxItems 2
     */
    origoLatLon: [number, number];
    /**
     * Resolution [m] of simulation grid. The simulation-grid is centered on origoLatLon
     */
    resolution: number;
    /**
     * Maximum location error [m] to accept, default should be 200.0 .
     */
    maxLocationError?: number;
    /**
     * Standard deviation of RF Sensors direction accuracy [deg]. Default should be 5.0 .
     */
    rfDirErrorStdDev: number;
    /**
     * Maximum detection range [m] of sensors. Default is 1000.0m (as specified in Watchdog/Wolfpack product sheets. Depending on environment and site-survey measurements others can be tried, e.g. 2000, 3000 or 4000 at the extreme.
     */
    rfMaxDetectionRange: number;
    /**
     * When estimating the max detection range of the combined set of RF-sensors, this defines the increment (resolution) of the boundary in [deg]. Set to 1.0 or 0.5deg as default.
     */
    rfMaxDetectionRangeBoundaryIncrement: number;
    /**
     * Width (x) and height (y) of simulated area [m]. The rectangle is centered on origoLatLon.
     *
     * @minItems 2
     * @maxItems 2
     */
    areaSpanXY: [number, number];
    /**
     * List of sensors to include
     */
    sensors: {
        /**
         * Unique ID of the sensor
         */
        sensorId: string;
        /**
         * GNSS latitude, longitude [decimal degrees] of sensor position
         *
         * @minItems 2
         * @maxItems 2
         */
        posLatLon: [number, number];
        /**
         * Azimuth facing/direction [deg] of sensor. East is 0 deg and North is 90 deg.
         */
        azimuthDir: number;
        /**
         * Azimuth opening [deg] of sensor. Default is 90deg for a Watchdog, 360deg for Wolfpack. If an opening of 360deg is specified, the azimuthDir must be 0.
         */
        azimuthOpen: number;
    }[];
};
