/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
/**
 * The related rfGeoThreatSimulationStart-message has not been accepted and a simulation is not started.
 */
export type RfGeoThreatSimulationStartError = {
    /**
     * Unique simulation number from rfGeoThreatSimulationRequest.
     */
    simulationNumber: number;
    /**
     * Textual error message.
     */
    errorInfo: string;
};
