/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
/**
 * List of RF segment recording. MyDefence internal and subject to change without notice.
 */
export type RfRecordList = {
    /**
     * Type of recording
     */
    recType: "threat" | "snapshot";
    /**
     * Type of threat that triggered the recording. Set for recType `threat`. Number refers to `id` in DeviceMiscellaneous:droneList.
     */
    threatType?: number;
    /**
     * Timestamp of when recording was created
     */
    createdTimeStamp: string;
    /**
     * Path to the recording data. Can be fetched from http://<argos-ip:28230>/<filePath>
     */
    filePath: string;
}[];
