/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
/**
 * Configure recording of RF segment information for threats. MyDefence internal and subject to change without notice.
 */
export type RfRecordThreatsConfig = {
    /**
     * List of devices (deviceIds) used for recording. Empty list means disable recording.
     */
    devices: string[];
    /**
     * Types of threats to trigger a recording. If empty any threat will trigger. Number refers to `id` in DeviceMiscellaneous:droneList.
     */
    threatTypes: number[];
    /**
     * If set, triggering of recordings will be disabled after this many seconds. Otherwise recordings will be triggered until explicitly reconfigured.
     */
    timeout?: number;
};
