/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export type SapientNode = {
    /**
     * ULID of this node
     */
    nodeId: string;
    /**
     * Current state of the node
     */
    nodeState: "connecting" | "registering" | "registrationFailed" | "connected" | "disconnecting" | "disconnected";
};
