/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export type SapientConfigure = {
    /**
     * Device serial number
     */
    deviceSerialNumber: string;
    /**
     * IP address of the Sapient data agent
     */
    sdaIp: string;
    /**
     * Port of the Sapient data agent
     */
    sdaPort: number;
}[];
