/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
/**
 * A unique serialnumber
 */
export type Serialnumber = string | null;
/**
 * The name of the module
 */
export type ModuleName = string;
/**
 * The name of the branch
 */
export type BranchName = string;
/**
 * The comitt hash id
 */
export type ComittHash = string;
/**
 * Defines the time of the build
 */
export type BuildDateTime = string | null;
/**
 * Defines the version
 */
export type Version = string | null;
/**
 * Defines the time of the version
 */
export type VersionDateTime = string | null;
/**
 * Timestamp
 */
export type Timestamp = string | null;
/**
 * Start timestamp
 */
export type StartTimestamp = string | null;
/**
 * The current state
 */
export type CurrentState = "running" | "closed";
/**
 * The uptime of the specific service
 */
export type Uptime = number;
/**
 * The update interval
 */
export type Interval = number | null;
export type SystemState = {
    [k: string]: {
        serialNumber: Serialnumber;
        moduleName: ModuleName;
        versionInfo?: VersionInfo;
        timestamp?: Timestamp;
        startTime?: StartTimestamp;
        currentState?: CurrentState;
        upTime?: Uptime;
        interval?: Interval;
    };
};
/**
 * The version object
 */
export type VersionInfo = {
    branch: BranchName;
    commitHash: ComittHash;
    buildDateTime: BuildDateTime;
    version: Version;
    versionDateTime: VersionDateTime;
};
