/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
/**
 * A unique serialnumber
 */
export type Serialnumber = string | null;
/**
 * The name of the module
 */
export type ModuleName = string;
/**
 * The name of the branch
 */
export type BranchName = string;
/**
 * The comitt hash id
 */
export type CommitHash = string;
/**
 * Defines the time of the build
 */
export type BuildDateTime = string;
/**
 * Defines the version
 */
export type Version = string;
/**
 * Defines the time of the version
 */
export type VersionDateTime = string;
/**
 * Timestamp
 */
export type TimestampOnlyAvailableInActualSystemComponents = string | null;
/**
 * The current state. Only available in actual system components.
 */
export type CurrentState = "running" | "closed";
/**
 * The uptime of the specific service. Only available in actual system components.
 */
export type Uptime = number;
/**
 * The update interval. Only available in actual system components.
 */
export type Interval = number | null;
/**
 * The system state object. Provides detailed about system components. Also contains a meta component (key: ARGOS) describing the system in its entirety.
 */
export type SystemState = {
    [k: string]: {
        serialNumber: Serialnumber;
        moduleName: ModuleName;
        versionInfo?: VersionInfo;
        timestamp?: TimestampOnlyAvailableInActualSystemComponents;
        currentState?: CurrentState;
        upTime?: Uptime;
        interval?: Interval;
    };
};
/**
 * The version object. Only available in the meta component.
 */
export type VersionInfo = {
    branch: BranchName;
    commitHash: CommitHash;
    buildDateTime: BuildDateTime;
    version: Version;
    versionDateTime: VersionDateTime;
};
