/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export type TakConfiguration = {
    /**
     * Callsign used CoT messages.
     */
    callsign: string;
    /**
     * When this is set, use the location of the specified device to broadcast Argos' location (using CoT event type a-f-G-E-V). The device should probably have useGpsLocation enabled. If not set Argos location will not be broadcast. Primarily relevant with vehicle systems.
     */
    locationDeviceId?: string;
    transports: ({
        type: "multicast";
        /**
         * Name of transport
         */
        name: string;
        /**
         * IP address of the Argos server
         */
        localIpAddress: string;
        /**
         * Multicast IP address
         */
        multicastIpAddress: string;
        /**
         * Multicast port number
         */
        port: number;
        options: TakTransportOptionsConfiguration;
        /**
         * Transport ID
         */
        transportId: string;
    } | {
        type: "tcp";
        /**
         * Name of transport
         */
        name: string;
        /**
         * TAK server IP address
         */
        address: string;
        /**
         * TAK server TCP port
         */
        port: number;
        options: TakTransportOptionsConfiguration;
        /**
         * Transport ID
         */
        transportId: string;
    } | {
        type: "tls";
        /**
         * Name of transport
         */
        name: string;
        /**
         * TAK server IP address
         */
        address: string;
        /**
         * TAK server TLS port
         */
        port: number;
        credentials: {
            /**
             * Credential ID. Use when modifying an existing transport. Credentials can't be modified
             */
            credentialId: string;
        };
        /**
         * Verify server certificate
         */
        verifyServer: boolean;
        options: TakTransportOptionsConfiguration;
        /**
         * Transport ID
         */
        transportId: string;
    } | {
        type: "tcpServer";
        /**
         * Name of transport
         */
        name: string;
        /**
         * TAK server TCP port
         */
        port: number;
        options: TakTransportOptionsConfiguration;
        /**
         * Transport ID
         */
        transportId: string;
    })[];
};
export type TakTransportOptionsConfiguration = {
    /**
     * Direction of CoT messages. `off` can be used to temporarily disable the transport.
     */
    direction: "input" | "output" | "both" | "off";
    /**
     * Filter uthreats on confidence before output
     */
    threshold: number;
};
