/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export type TakConfiguration = {
    /**
     * Callsign used for CoT messages.
     */
    callsign: string;
    /**
     * When this is set, broadcast the location of the specified device using CoT event type `a-f-G-E-V` - Ground Equipment Vehicle. The device should probably have useGpsLocation enabled. For vehicle systems. When false, broadcast mission center information using CoT event type `a-f-G-U-H` - Special C2 Headquarters. The CoT object in either case contain the configured callsign, and be used as parent link in threat details.
     */
    vehicleDeviceId?: string;
    /**
     * When true, broadcast location of all devices using CoT messages.
     */
    sendLocations: boolean;
    /**
     * When true, broadcast threat details using proprietary CoT message properties. For interworking with other MyDefence systems or wearables. Setting this will also set `sendLocations` to true.
     */
    sendThreatDetails: boolean;
    transports: ({
        type: "multicast";
        /**
         * Name of transport
         */
        name: string;
        /**
         * IP address of the Argos server
         */
        localIpAddress: string;
        /**
         * Multicast IP address
         */
        multicastIpAddress: string;
        /**
         * Multicast port number
         */
        port: number;
        options: TakTransportOptionsConfiguration;
        /**
         * Transport ID
         */
        transportId: string;
    } | {
        type: "tcp";
        /**
         * Name of transport
         */
        name: string;
        /**
         * TAK server IP address
         */
        address: string;
        /**
         * TAK server TCP port
         */
        port: number;
        options: TakTransportOptionsConfiguration;
        /**
         * Transport ID
         */
        transportId: string;
    } | {
        type: "tls";
        /**
         * Name of transport
         */
        name: string;
        /**
         * TAK server IP address
         */
        address: string;
        /**
         * TAK server TLS port
         */
        port: number;
        credentials: {
            /**
             * Credential ID. Use when modifying an existing transport. Credentials can't be modified
             */
            credentialId: string;
        };
        /**
         * Verify server certificate
         */
        verifyServer: boolean;
        options: TakTransportOptionsConfiguration;
        /**
         * Transport ID
         */
        transportId: string;
    } | {
        type: "tcpServer";
        /**
         * Name of transport
         */
        name: string;
        /**
         * TAK server TCP port
         */
        port: number;
        options: TakTransportOptionsConfiguration;
        /**
         * Transport ID
         */
        transportId: string;
    })[];
};
export type TakTransportOptionsConfiguration = {
    /**
     * Direction of CoT messages. `off` can be used to temporarily disable the transport.
     */
    direction: "input" | "output" | "both" | "off";
    /**
     * Filter uthreats on confidence before output
     */
    threshold: number;
};
