/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export type TakTransportList = TakTransport[];
export type TakTransport = {
    /**
     * Unique ID of this TAK tansport
     */
    transportId: string;
    /**
     * Current state of the TAK transport
     */
    transportState: "off" | "connecting" | "connected" | "listening" | "error";
    /**
     * List of clients connected to this transport. Only present when transportState is 'listening'
     */
    clients?: string[];
    /**
     * Error information. Will be set when transportState is 'error' and can be set if transportState is 'connecting
     */
    errorInfo?: string;
};
