/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export type ThreatType = {
    /**
     * Defines the threat name from the threat library
     */
    threatName?: string;
    /**
     * Defines a unique number for the threat type
     */
    threatType: number;
};
