/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
/**
 * User capabilities. These are used to determine which requests a user can perform. The required capabilities for individual requests can be seen from `argosApiCapabilities.ts` or from the interface specification document.
 */
export type UserCapability = "CAP_C2_ECM" | "CAP_C2_ECM_GNSS" | "CAP_C2_ECM_STOP" | "CAP_C2_CONFIG" | "CAP_C2_MUTE" | "CAP_SYS_CONFIG" | "CAP_SYS_USERMGMT" | "CAP_DISABLED";
export type UserWelcome = {
    /**
     * Username of the logged-in user
     */
    username: string;
    /**
     * Full name of the logged-in user
     */
    fullname: string;
    /**
     * List of capabilities assigned to the user
     */
    capabilities: UserCapability[];
};
