/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export type UthreatConfig = {
    /**
     * Choose level of sensor fusion. None: No fusion; RF: Fusion of RF sensor into RF geolocation; All: Fusion of RF geolocation and radars. Default setting is all.
     */
    fuseLevel?: "none" | "rf" | "all";
    /**
     * This can be used by the application to store a threshold for when a uthreat is displayed as a drone. The value is not used in the backend, and will not affect which uthreats are sent on the API. The value will be stored in the uthreat archive for forensics. This schema files provides some example values.
     */
    droneConfidenceThreshold?: (0.1 | 0.5 | 0.9 | 0.92 | number) & number;
};
