/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
export type UthreatSetMute = {
    /**
     * The unique ID of the uthreat to mute/unmute. Corresponds to the same field in uthreat messages.
     */
    uthreatId: string;
    /**
     * Mute-value to set, if true the uthreat will be muted.
     */
    mute: boolean;
};
