/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
/**
 * A unique system identification, generated automatically from the system
 */
export type StreamIdentification = string;
/**
 * Video Device ID
 */
export type VideoDeviceID = string;
/**
 * Sub device ID from ptzDeviceInfo if relevant
 */
export type VideoSubDeviceID = number;
/**
 * A description of the source of the video
 */
export type StreamDescription = string;
export type VmsType = "daylight" | "IR" | "thermal";
/**
 * IP address of camera tube
 */
export type IPAddress = string;
export type VmsStreamList = {
    vmsStreamId: StreamIdentification;
    videoDeviceId: VideoDeviceID;
    videoSubDeviceId?: VideoSubDeviceID;
    description: StreamDescription;
    vmsType?: VmsType;
    streamIp: IPAddress;
    /**
     * All stream info from the camera. Content depends on camera
     */
    rawStreamInfo: {
        [k: string]: unknown;
    };
}[];
