/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
/**
 * A unique stream identification, generated automatically from the system
 */
export type StreamIdentification = string;
/**
 * SDP offer for WebRTC initialization in unencoded text
 */
export type SDPOffer = string;
export type VmsSdpInit = {
    vmsStreamId: StreamIdentification;
    sdpOffer: SDPOffer;
};
