/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
/**
 * SDP reply for WebRTC initialization in unencoded text
 */
export type SDPReply = string;
export type VmsSdpInitCompleted = {
    sdpReply: SDPReply;
};
